- name: Building Image
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/base.yml
  become: True
  become_user: root
  remote_user: root
  tasks:
    - name: Build And Install
      include_tasks:
        file: jobs/build/build.yml
